### ISSUE TITLE
add shellexpand and glob

### ISSUE THREAD

**Issue by vitiral** [rust-crates/ergo_fs#1]
## Glob
Add functions `glob` and `glob_with` which are identical to the ones in the glob crate _except_ they return an iterator of `PathType` objects instead of simple paths.

This should really have https://github.com/rust-lang-nursery/glob/issues/64 implemented so that `GlobError` is coercible into `io::Error`. `GlobError` already provides excellent context.

## Shellexpand
This will mainly involve exporting the [shellexpand](https://docs.rs/shellexpand) module, but the trait mentioned in https://github.com/netvl/shellexpand/issues/2 would probably improve the ergonomics.

I have read through the shellexpand source code and I think it has ergonomic error messages.

**Comment by vitiral** [comment]
@killercup thoughts?

**Comment by killercup** [comment]
FYI https://twitter.com/killercup/status/957691964694188033

**Comment by vitiral** [comment]
I can do that. You want to include ergo_fs into quicli?

- sent from my Android

**Comment by killercup** [comment]
@gilnaa is already working on it.

Not sure if I want to include (parts of) it in quicli or I use a subset of its re-exports and add documentation about where to find more.

**Comment by vitiral** [comment]
So I'm thinking of doing PathType::glob,
PathFile::glob, PathDir::glob

(and also the same for glob_with)

This will give the choice of what types they want. Thoughts?

**Comment by vitiral** [comment]
Ok, I think that was the wrong approach.

Instead on my `GlobPaths` object I'm going to have a `files()` method that only returns files. I think that is the right approach.

This could honestly be added to the `glob` crate as well. I think I'm going to add a PR.

Update: see issue https://github.com/rust-lang-nursery/glob/issues/65

**Comment by vitiral** [comment]
done

**Comment by vitiral** [comment]
@killercup I recommend not exporting `ergo_fs` wholesale yet, as I think I'm going to remove the `std_prelude` export and replace it with only `Path`, `PathBuf`, `Read` and `Write`.
